/**
 * Live pixel renderer for the world map.
 *
 * The terrain comes from src/data/worldmap.json (generated by tools/worldmap.py): a base colour layer,
 * a terrain-kind layer and an area layer (one area per civilization). Every frame we recolour tiles
 * from game state — this cycle's events, melting snow and rising seas as the climate warms — then
 * draw the animated scenery (boats, lighthouse, dam) and each town: its keep plus every building the
 * player has built, filling the town's plots nearest-first so the town visibly grows.
 * Pure function over a pixel buffer: no DOM, so it is testable in Node.
 */
import world from "../../../../src/data/worldmap.json";
import oceanData from "../../../../src/data/ocean.json";
import { EVENTS } from "./content";
import { spillTarget } from "./engine";
import { OWNERS, TOWNS } from "./towns";
import { CIV_IDS, type CivId, type GameState } from "./types";

export const MAP_W = world.w;
export const MAP_H = world.h;
export const OCEAN = oceanData;
type RGB = [number, number, number];
const rgb = (hex: string): RGB => [
  parseInt(hex.slice(1, 3), 16),
  parseInt(hex.slice(3, 5), 16),
  parseInt(hex.slice(5, 7), 16),
];
const KIND = Object.fromEntries(world.kinds.map((k, i) => [k, i])) as Record<
  string,
  number
>;
const NONE = 255;

const C = {
  fissure: rgb("#3e2414"),
  shimmer: rgb("#e8f6fb"),
  seaShallow: rgb("#3a8bbd"),
  seaMid: rgb("#2b6fa0"),
  waveMark: rgb("#21497a"),
  deep: rgb(OCEAN.deep),
  sea: rgb("#21497a"),
  crest: rgb(OCEAN.crest),
  ink: rgb("#1a120a"),
  rock: rgb("#776e60"),
  rockD: rgb("#5c554a"),
  shallow: rgb("#2b6fa0"),
  flood: rgb("#6ab8cc"),
  foam: rgb("#9fd6e4"),
  wave: rgb("#3b6ea8"),
  murk: rgb("#3c5446"),
  char: rgb("#2a221c"),
  charD: rgb("#16110e"),
  ember: rgb("#f06020"),
  emberY: rgb("#ffe14a"),
  mud: rgb("#6e4c2a"),
  wetSand: rgb("#b8a06a"),
  debris: rgb("#5e3c20"),
  soil: rgb("#8a6238"),
  dry: rgb("#b8982e"),
  sludge: rgb("#6e6230"),
  sludgeD: rgb("#4e4520"),
  smoke: rgb("#c9c9c9"),
  smokeD: rgb("#6b6b72"),
};
// Territory (including Harborkeep's desert shore) is baked into the map's terrain by the generator
// with ordered dithering, so the renderer paints no translucent washes over the land.
const FLAG: Record<string, RGB> = {
  highland: rgb("#a07ad6"),
  verdant: rgb("#7fd65a"),
  forge: rgb("#f08a3c"),
  tidehaven: rgb("#46d6d0"),
};

export interface WorldLayers {
  base: Uint8Array;
  palette: RGB[];
  kind: Uint8Array;
  area: Uint8Array;
  near: Uint8Array;
  distWater: Uint8Array;
  distSea: Uint8Array;
  /** For sea tiles: how far out from the shore (1 = touching land). */
  distLand: Uint8Array;
  /** For inland water: 1 at the bank, growing toward the middle. */
  depth: Uint8Array;
  /** Distance to water at least 4px from any bank: small only in and around the reservoir. */
  nearDeep: Uint8Array;
  hash: Uint8Array;
}

function unrle(runs: number[]): Uint8Array {
  const out = new Uint8Array(MAP_W * MAP_H);
  let o = 0;
  for (let i = 0; i < runs.length; i += 2) {
    out.fill(runs[i], o, o + runs[i + 1]);
    o += runs[i + 1];
  }
  return out;
}
function fromBase64(s: string): Uint8Array {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
/** 4-neighbour distance (capped at 255) from every tile matching `source`. */
function distance(kind: Uint8Array, source: (k: number) => boolean) {
  const dist = new Uint8Array(kind.length).fill(255);
  let frontier: number[] = [];
  kind.forEach((k, i) => {
    if (source(k)) {
      dist[i] = 0;
      frontier.push(i);
    }
  });
  for (let d = 1; d < 255 && frontier.length; d++) {
    const next: number[] = [];
    for (const i of frontier) {
      const x = i % MAP_W;
      for (const j of [
        i - MAP_W,
        i + MAP_W,
        x > 0 ? i - 1 : -1,
        x < MAP_W - 1 ? i + 1 : -1,
      ])
        if (j >= 0 && j < kind.length && dist[j] === 255) {
          dist[j] = d;
          next.push(j);
        }
    }
    frontier = next;
  }
  return dist;
}

let cached: WorldLayers | undefined;
export function worldLayers(): WorldLayers {
  if (cached) return cached;
  const kind = unrle(world.kind);
  const hash = new Uint8Array(MAP_W * MAP_H);
  for (let i = 0; i < hash.length; i++) {
    let h = Math.imul(i ^ 0x9e3779b9, 0x85ebca6b);
    h = Math.imul(h ^ (h >>> 13), 0xc2b2ae35);
    hash[i] = (h ^ (h >>> 16)) & 255;
  }
  const depth = distance(kind, (k) => k !== KIND.water);
  cached = {
    base: fromBase64(world.base),
    palette: world.palette.map(rgb),
    kind,
    area: unrle(world.area),
    near: unrle(world.near),
    distWater: distance(kind, (k) => k <= KIND.water),
    distSea: distance(kind, (k) => k <= KIND.shallow),
    distLand: distance(kind, (k) => k > KIND.shallow),
    depth,
    nearDeep: distance(depth, (d) => d >= 4),
    hash,
  };
  return cached;
}

const isSea = (k: number) => k <= KIND.shallow;
const lowland = (k: number) =>
  k === KIND.grass ||
  k === KIND.pasture ||
  k === KIND.field ||
  k === KIND.marsh ||
  k === KIND.beach ||
  k === KIND.forest;
const mix = (a: RGB, b: RGB, t: number): RGB => [
  a[0] + (b[0] - a[0]) * t,
  a[1] + (b[1] - a[1]) * t,
  a[2] + (b[2] - a[2]) * t,
];

/** One world-coordinate texture for the entire sea, including beyond the map bounds. */
export function seaPixel(
  x: number,
  y: number,
  frame: number,
  climate = 0,
): RGB {
  const CELL = 16;
  const drift = Math.floor(frame / 24); // one pixel every 4 seconds
  const wx = x + drift;
  const cx = Math.floor(wx / CELL),
    cy = Math.floor(y / CELL);
  let h = Math.imul((cx * 73856093) ^ (cy * 19349663) ^ 0x9e3779b9, 0x85ebca6b);
  h = Math.imul(h ^ (h >>> 13), 0xc2b2ae35);
  h = (h ^ (h >>> 16)) >>> 0;
  const ox = 2 + (h % 11),
    oy = 2 + ((h >>> 8) % 11);
  const dx = wx - cx * CELL - ox,
    dy = y - cy * CELL - oy;
  let c = C.deep;
  // a small "~": low-high-low over three pixels
  if (
    (dx === 0 && dy === 1) ||
    (dx === 1 && dy === 0) ||
    (dx === 2 && dy === 1)
  )
    c = C.waveMark;
  const health = 100 - climate * 12;
  if (health < 85) c = mix(c, C.murk, Math.min(0.6, (85 - health) / 100));
  return c;
}

/**
 * Sea colour by distance from shore: foam (1px, broken, rocking 1px every 500ms) → shallow (4px) →
 * mid (8px) → deep with wave marks. One set of bands, no repeated rings.
 */
function oceanPixel(
  L: WorldLayers,
  i: number,
  x: number,
  y: number,
  frame: number,
  climate: number,
): RGB {
  const d = L.distLand[i];
  const phase = Math.floor(frame / 3) % 2; // 3 frames at 6fps = 500ms
  if (d === 1 + phase && (x * 3 + y * 7) % 9 !== 0) return C.shimmer;
  let c =
    d <= 4 ? C.seaShallow : d <= 12 ? C.seaMid : seaPixel(x, y, frame, climate);
  const health = 100 - climate * 12;
  if (d <= 12 && health < 85)
    c = mix(c, C.murk, Math.min(0.6, (85 - health) / 100));
  return c;
}

export interface PortTraffic {
  civ: CivId;
  frame: number;
}
/** Trade notices are synchronized through the pure reducer and SpacetimeDB state. */
export function tradeTraffic(
  state: GameState | undefined,
  frame: number,
): PortTraffic[] {
  return (state?.news ?? [])
    .filter((n) => n.kind === "trade" && n.round === state?.round && n.civ)
    .slice(-OCEAN.trade.maxBoats)
    .map((n, i) => ({
      civ: n.civ!,
      frame: (frame + i * 7) % OCEAN.trade.frames,
    }));
}

const routes = new Map<CivId, [number, number][]>();
/** Find a berth and a connected sailing route. Ships never cross land tiles. */
export function portRoute(civ: CivId): [number, number][] {
  const cachedRoute = routes.get(civ);
  if (cachedRoute) return cachedRoute;
  const L = worldLayers();
  const anchor = OCEAN.ports[civ];
  let start = -1,
    closest = Infinity;
  const touchesLand = (i: number) => {
    const x = i % MAP_W;
    return [
      x > 0 ? i - 1 : -1,
      x < MAP_W - 1 ? i + 1 : -1,
      i - MAP_W,
      i + MAP_W,
    ].some((j) => j >= 0 && j < L.kind.length && L.kind[j] > KIND.water);
  };
  for (let i = 0; i < L.kind.length; i++) {
    if (L.kind[i] > KIND.water || !touchesLand(i)) continue;
    const d =
      Math.abs((i % MAP_W) - anchor[0]) +
      Math.abs(Math.floor(i / MAP_W) - anchor[1]);
    if (d < closest) {
      start = i;
      closest = d;
    }
  }
  const parents = new Map<number, number>([[start, -1]]);
  let frontier = [start],
    end = start;
  for (
    let step = 0;
    step < OCEAN.trade.routeLength && frontier.length;
    step++
  ) {
    const next: number[] = [];
    for (const i of frontier) {
      const x = i % MAP_W;
      for (const j of [
        x > 0 ? i - 1 : -1,
        x < MAP_W - 1 ? i + 1 : -1,
        i - MAP_W,
        i + MAP_W,
      ]) {
        if (
          j < 0 ||
          j >= L.kind.length ||
          L.kind[j] > KIND.water ||
          parents.has(j)
        )
          continue;
        parents.set(j, i);
        next.push(j);
        end = j;
      }
    }
    frontier = next;
  }
  const path: [number, number][] = [];
  for (let i = end; i >= 0; i = parents.get(i) ?? -1)
    path.push([i % MAP_W, Math.floor(i / MAP_W)]);
  path.reverse();
  routes.set(civ, path);
  return path;
}

export function tsunamiDirection(state: GameState): string {
  return OCEAN.tsunami.sides[
    ((state.seed >>> 0) + state.round) % OCEAN.tsunami.sides.length
  ];
}

export interface WorldView {
  width: number;
  height: number;
  originX: number;
  originY: number;
  /** The map's safe area; waves and sea continue behind the surrounding UI. */
  clip: { left: number; top: number; right: number; bottom: number };
}

/** Composite the island and extended sea on one pixel grid and one animation clock. */
export function renderWorldView(
  state: GameState | undefined,
  frame: number,
  out: Uint8ClampedArray,
  view: WorldView,
  traffic = tradeTraffic(state, frame),
  strikeAge = Infinity,
) {
  const { width, height, originX, originY, clip } = view;
  for (let y = 0; y < height; y++)
    for (let x = 0; x < width; x++) {
      const c = seaPixel(x - originX, y - originY, frame, state?.climate);
      const o = (y * width + x) * 4;
      out[o] = c[0];
      out[o + 1] = c[1];
      out[o + 2] = c[2];
      out[o + 3] = 255;
    }
  const island = new Uint8ClampedArray(MAP_W * MAP_H * 4);
  renderWorld(state, frame, island, traffic, strikeAge);
  for (let y = 0; y < MAP_H; y++)
    for (let x = 0; x < MAP_W; x++) {
      const tx = x + originX,
        ty = y + originY;
      if (
        tx < 0 ||
        ty < 0 ||
        tx >= width ||
        ty >= height ||
        tx < clip.left ||
        ty < clip.top ||
        tx >= clip.right ||
        ty >= clip.bottom
      )
        continue;
      const o = (ty * width + tx) * 4,
        i = (y * MAP_W + x) * 4;
      out.set(island.subarray(i, i + 4), o);
    }
  const active =
    state &&
    state.phase !== "ended" &&
    areaStatus(state).some((a) => a.active.has("tsunami"));
  if (!active) return;
  const side = tsunamiDirection(state);
  const alongX = side !== "south",
    extent = alongX ? width : height;
  const progress = (frame % OCEAN.tsunami.frames) / (OCEAN.tsunami.frames - 1);
  const front = Math.floor(-12 + progress * (extent + 24));
  const L = worldLayers();
  for (let y = 0; y < height; y++)
    for (let x = 0; x < width; x++) {
      const wx = x - originX,
        wy = y - originY;
      const inMap = wx >= 0 && wy >= 0 && wx < MAP_W && wy < MAP_H;
      const i = wy * MAP_W + wx;
      // Only the sea and low coastal ground are swept. Inland hills remain readable.
      if (
        inMap &&
        L.kind[i] > KIND.water &&
        (L.distSea[i] > OCEAN.tsunami.coastalReach || !lowland(L.kind[i]))
      )
        continue;
      const axis =
        side === "east" ? width - 1 - x : side === "south" ? height - 1 - y : x;
      const bend = Math.floor((alongX ? y : x) / 9) % 3;
      const d = front + bend - axis;
      if (d < 0 || d >= OCEAN.tsunami.width) continue;
      const c = d < 2 ? C.crest : d < 4 ? C.foam : d < 6 ? C.flood : C.shallow;
      const o = (y * width + x) * 4;
      out[o] = c[0];
      out[o + 1] = c[1];
      out[o + 2] = c[2];
    }
}

/** Frames a disaster takes to sweep in when it is revealed (about 3s at the map's 6fps). */
export const STRIKE_FRAMES = 18;
const ACTIVE_PHASES = new Set(["event", "quiz", "response", "choice"]);

export interface AreaStatus {
  /** Everything touching this region this decade (raging or aftermath). */
  effects: Set<string>;
  /** Hazards still raging: from the reveal until the town has made its choice. */
  active: Set<string>;
  /** Scars left behind, by event: strength 0..1 and the decade it struck. */
  after: Map<string, { strength: number; round: number }>;
  buildings: string[];
  /** 1 while a hazard rages; the scar strength afterwards (drives smoke over the keep). */
  damaged: number;
}
/** How much damage a response leaves behind: braced = all of it, sustainable = less, cheap = none here. */
const SCAR = (option: number | undefined) =>
  option === 0 ? 0 : option === 1 ? 0.6 : 1;
/** What is happening in each town's region right now. */
export function areaStatus(state?: GameState): AreaStatus[] {
  return TOWNS.map((t) => {
    const civ = OWNERS[t.civ];
    const effects = new Set<string>();
    const active = new Set<string>();
    const after = new Map<string, { strength: number; round: number }>();
    let damaged = 0;
    const scar = (event: string, strength: number, round: number) => {
      if (strength <= 0) return;
      const prev = after.get(event);
      if (!prev || prev.strength < strength)
        after.set(event, { strength, round });
      damaged = Math.max(damaged, strength);
    };
    if (state && state.phase !== "ended") {
      const own = state.events[civ];
      if (own && ACTIVE_PHASES.has(state.phase)) {
        active.add(own.type);
        effects.add(own.type);
        damaged = 1;
      }
      if (own && state.phase === "build") {
        // The hazard is over: what's left depends on how the town responded.
        const strength = SCAR(state.civs[civ].choice);
        if (strength > 0) effects.add(own.type);
        scar(own.type, strength, state.round);
        // Hazards a neighbor's cheap fix pushed onto this region.
        for (const other of CIV_IDS) {
          const e = EVENTS[state.events[other]?.type];
          if (
            other === civ ||
            state.civs[other].choice !== 0 ||
            !e?.cheap.spillTo
          )
            continue;
          if (spillTarget(other, e.cheap.spillTo) === civ) {
            effects.add(state.events[other].type);
            scar(state.events[other].type, 0.6, state.round);
          }
        }
      }
    }
    // Scars from earlier decades fade: 3 decades to heal, 2 after a sustainable response.
    for (const n of state?.news ?? []) {
      if (
        (n.kind !== "event" && n.kind !== "spill") ||
        n.civ !== civ ||
        !n.event
      )
        continue;
      const age = state!.round - n.round;
      if (age < 1) continue;
      const base = n.kind === "spill" ? 0.6 : SCAR(n.option);
      const heal = n.kind === "event" && n.option === 1 ? 2 : 3;
      scar(n.event, base * (1 - age / (heal + 1)), n.round);
    }
    return {
      effects,
      active,
      after,
      buildings: state
        ? ["house", "house", ...state.civs[civ].buildings]
        : ["house", "house"],
      damaged,
    };
  });
}
/** A small flame tile, three poses, flickered at the map's 6fps. */
const FLAME_TILES = [
  [".R.", "ROR", "OYO", ".O."],
  ["R..", ".RO", "OYO", ".O."],
  ["..R", "OR.", "OYO", ".O."],
];
const FLAME: Record<string, RGB> = {
  R: rgb("#d02818"),
  O: rgb("#f06020"),
  Y: rgb("#ffe14a"),
};
const FIRE_RADIUS = 30;
interface Fire {
  a: number;
  cx: number;
  cy: number;
  /** Current burning radius (grows during the strike). */
  r: number;
  /** Raging (flames) vs a scar (burnt ground). */
  burning: boolean;
  /** Scar strength 0..1. */
  strength: number;
  /** Scar from this decade (still smoldering). */
  fresh: boolean;
}
const ignitionPool = new Map<number, number[]>();
/** Where a town's fire starts in a given decade: forest or grass 10-20px from the keep. */
function ignition(L: WorldLayers, a: number, round: number): [number, number] {
  let pool = ignitionPool.get(a);
  const [cx, cy] = TOWNS[a].keepTile;
  if (!pool) {
    pool = [];
    for (let y = cy - 20; y <= cy + 20; y++)
      for (let x = cx - 20; x <= cx + 20; x++) {
        if (x < 0 || y < 0 || x >= MAP_W || y >= MAP_H) continue;
        const d = Math.hypot(x - cx, y - cy);
        const i = y * MAP_W + x;
        const k = L.kind[i];
        if (
          d >= 10 &&
          d <= 20 &&
          L.area[i] === a &&
          (k === KIND.forest || k === KIND.grass || k === KIND.pasture)
        )
          pool.push(i);
      }
    ignitionPool.set(a, pool);
  }
  if (!pool.length) return [cx, cy];
  const pick = pool[(Math.imul(round + 7, 2654435761) >>> 0) % pool.length];
  return [pick % MAP_W, (pick / MAP_W) | 0];
}
/** Every fire on the map this frame: raging ones spread out from their ignition during the strike. */
function fires(
  L: WorldLayers,
  state: GameState | undefined,
  status: AreaStatus[],
  progress: number,
): Fire[] {
  const out: Fire[] = [];
  status.forEach((st, a) => {
    for (const e of ["wildfire", "volcano"]) {
      if (st.active.has(e)) {
        const [cx, cy] = ignition(L, a, state?.round ?? 0);
        out.push({
          a,
          cx,
          cy,
          r: Math.max(2, FIRE_RADIUS * progress),
          burning: true,
          strength: 1,
          fresh: true,
        });
      }
      const scar = st.after.get(e);
      if (scar) {
        const [cx, cy] = ignition(L, a, scar.round);
        out.push({
          a,
          cx,
          cy,
          r: FIRE_RADIUS,
          burning: false,
          strength: scar.strength,
          fresh: scar.round === state?.round,
        });
      }
    }
  });
  return out;
}
const burnable = (k: number) =>
  k === KIND.forest || k === KIND.grass || k === KIND.pasture;

/**
 * Earthquake fissures for one town: five short jagged cracks running outward from near the keep,
 * one with a small branch. 1 = crack, 2 = dusty edge beside it. Computed once per town.
 */
const CRACKS = new Map<number, Uint8Array>();
function quakeCracks(a: number): Uint8Array {
  const cached = CRACKS.get(a);
  if (cached) return cached;
  const mask = new Uint8Array(MAP_W * MAP_H);
  const town = TOWNS[a];
  if (!town) return mask;
  let seed = (a + 1) * 2654435761;
  const rand = () => {
    seed = (Math.imul(seed, 1103515245) + 12345) >>> 0;
    return seed / 4294967296;
  };
  const mark = (x: number, y: number, v: 1 | 2) => {
    if (x < 0 || y < 0 || x >= MAP_W || y >= MAP_H) return;
    const i = y * MAP_W + x;
    if (v === 1 || !mask[i]) mask[i] = v;
  };
  const crack = (x0: number, y0: number, angle: number, length: number) => {
    let x = x0,
      y = y0;
    for (let s = 0; s < length; s++) {
      if (s % 2 === 0) angle += (rand() - 0.5) * 0.9; // jagged
      x += Math.cos(angle);
      y += Math.sin(angle) * 0.8;
      mark(Math.round(x), Math.round(y), 1);
      mark(Math.round(x) + 1, Math.round(y), 2);
    }
    return [x, y, angle] as const;
  };
  const [cx, cy] = town.keepTile;
  for (let k = 0; k < 5; k++) {
    const angle = k * 1.26 + rand() * 0.6;
    const r = 9 + rand() * 3;
    const [mx, my, ma] = crack(
      cx + Math.cos(angle) * r,
      cy + Math.sin(angle) * r * 0.8,
      angle,
      8 + Math.floor(rand() * 8),
    );
    if (k === 0) crack(mx, my, ma + 0.8, 5);
  }
  CRACKS.set(a, mask);
  return mask;
}

/** Snow at lower altitude melts first as the planet warms (climate is °C above baseline). */
const meltThreshold = (y: number, h: number) =>
  3 - (Math.min(y, 50) / 50) * 2.6 + (h / 255 - 0.5) * 0.4;

function terrainPixel(
  L: WorldLayers,
  i: number,
  frame: number,
  status: AreaStatus[],
  climate: number,
  ocean: number,
  progress: number,
  fireList: Fire[],
): RGB {
  const x = i % MAP_W,
    y = (i / MAP_W) | 0,
    k = L.kind[i],
    h = L.hash[i],
    a = L.area[i];
  let c: RGB = L.palette[L.base[i]];
  if (isSea(k)) c = oceanPixel(L, i, x, y, frame, climate);

  // Global state: melting snow, rising seas, ocean health.
  if (k === KIND.snow && climate > meltThreshold(y, h))
    c = h & 1 ? C.rock : C.rockD;
  const rise = Math.floor(climate * 1.5);
  const tidehaven = a !== NONE && TOWNS[a].civ === "tidehaven";
  if (
    rise > 0 &&
    L.distSea[i] <= rise &&
    (k === KIND.beach || (tidehaven && lowland(k)))
  )
    c = h < 40 ? C.flood : C.shallow;
  if (k === KIND.shallow && ocean < 85)
    c = mix(c, C.murk, Math.min(0.6, (85 - ocean) / 100));

  // Ambient animation: water shimmer and drifting waves.
  // River shimmer: sparse white glints that step downstream (down the map) on a 3-frame loop.
  if (k === KIND.water && h < 120 && (x * 5 + y - (frame % 3) * 2) % 13 === 0)
    c = C.shimmer;

  // Hazards in this area (sea tiles take the hazards of the nearest area).
  const owner = a !== NONE ? a : L.near[i];
  const fx = owner === NONE ? undefined : status[owner].active;
  const land = a !== NONE && !isSea(k);
  const p = progress; // 0 -> 1 while the disaster sweeps in
  const fresh = h / 255 < p; // a pixel the strike has reached
  // Distance from the struck town's keep, normalised (quake cracks race outward from it).
  const keepDist = (o: number) =>
    Math.hypot(x - TOWNS[o].keepTile[0], y - TOWNS[o].keepTile[1]) / 30;
  if (fx && fx.size) {
    for (const e of fx) {
      if (
        (e === "flood" || e === "dam_failure") &&
        land &&
        lowland(k) &&
        L.distWater[i] <= Math.round(4 * p)
      ) {
        c =
          ((x + y + (frame >> 1)) & 3) === 0
            ? C.foam
            : h < 90
              ? C.shallow
              : C.flood;
      } else if (
        (e === "hurricane" || e === "tsunami" || e === "sea_rise") &&
        land &&
        lowland(k) &&
        L.distSea[i] <= Math.round(5 * p)
      ) {
        c = ((x - y + (frame >> 1)) & 3) === 0 ? C.foam : C.flood;
      } else if (e === "spill" && (isSea(k) || k === KIND.water) && fresh) {
        const band = (x + 2 * y + (frame >> 1)) % 6;
        if (band === 0) c = C.sludge;
        else if (band === 1) c = C.sludgeD;
      } else if (
        (e === "smog" || e === "heatwave") &&
        (x + 2 * y) % 5 === 0 &&
        fresh
      ) {
        c = mix(c, rgb(EVENTS[e as keyof typeof EVENTS].color), 0.5);
      } else if (e === "drought" && land) {
        // Patchy, not total: keeps the area readable while showing it has dried out.
        if (
          (k === KIND.grass || k === KIND.pasture || k === KIND.field) &&
          h < 110 * p
        )
          c = mix(c, h < 55 ? C.dry : C.soil, 0.7);
        else if (k === KIND.water) {
          if (L.depth[i] === 1 && L.nearDeep[i] <= 3)
            c = h < 128 ? C.soil : C.dry; // exposed lakebed
          else c = mix(c, C.shimmer, 0.18);
        }
      } else if ((e === "earthquake" || e === "landslide") && land) {
        // A few short jagged fissures around the struck town (no region-wide lines).
        const crack = keepDist(owner) <= p ? quakeCracks(owner)[i] : 0;
        if (crack === 1) c = C.fissure;
        else if (crack === 2) c = mix(c, C.soil, 0.55);
        else if (e === "landslide" && L.distWater[i] <= 2 && h < 100)
          c = C.soil;
      } else if (e === "grid_failure" && land) {
        // the lights flicker out during the strike, then stay dark
        if (p >= 1 || frame & 1) c = mix(c, C.ink, 0.35);
      } else if (e === "pandemic" && land && (x + y * 2) % 7 === 0 && fresh) {
        c = mix(c, rgb(EVENTS.pandemic.color), 0.55);
      } else if (e === "supply_shock" && land && h < 70 && fresh) {
        c = mix(c, rgb(EVENTS.supply_shock.color), 0.35);
      }
    }
  }
  // Aftermath: scars from this and earlier decades, healing patchily as their strength falls.
  const scars = owner === NONE ? undefined : status[owner].after;
  if (scars && scars.size)
    for (const [e, { strength }] of scars) {
      const scarred = h / 255 < strength; // healed pixels show the land again
      if (
        (e === "flood" || e === "dam_failure") &&
        land &&
        lowland(k) &&
        L.distWater[i] <= 3 &&
        scarred
      )
        c = h % 7 === 0 ? C.flood : mix(c, C.mud, 0.6); // mud and puddles
      else if (
        (e === "hurricane" || e === "tsunami" || e === "sea_rise") &&
        land &&
        lowland(k) &&
        L.distSea[i] <= 4 &&
        scarred
      )
        c = h % 9 === 0 ? C.debris : mix(c, C.wetSand, 0.5); // wet sand and debris
      else if (
        e === "spill" &&
        (isSea(k) || k === KIND.water) &&
        scarred &&
        (x + 2 * y) % 6 === 0
      )
        c = C.sludgeD; // stained water
      else if (
        (e === "smog" || e === "heatwave") &&
        (x + 2 * y) % 9 === 0 &&
        scarred
      )
        c = mix(c, rgb(EVENTS[e as keyof typeof EVENTS].color), 0.3);
      else if (
        e === "drought" &&
        land &&
        (k === KIND.grass || k === KIND.pasture || k === KIND.field) &&
        h < 110 &&
        scarred
      )
        c = (x * 3 + y) % 11 === 0 ? C.soil : mix(c, C.dry, 0.5); // cracked earth
      else if ((e === "earthquake" || e === "landslide") && land) {
        const crack = quakeCracks(owner)[i];
        if (crack === 1) c = mix(c, C.fissure, strength);
        else if (crack === 2) c = mix(c, C.soil, 0.55 * strength);
      } else if (e === "grid_failure" && land && scarred)
        c = mix(c, C.ink, 0.12);
    }

  // Wildfire: a burn spreading from where it started, then a scar that heals patchily.
  if (burnable(k))
    for (const f of fireList) {
      const d = Math.hypot(x - f.cx, y - f.cy);
      const rim = f.r + ((h % 5) - 2); // slightly uneven edge
      if (d > rim) continue;
      if (f.burning) {
        if (d > rim - 2)
          c = ((frame + h) & 1) === 0 ? C.ember : C.emberY; // the advancing front
        else c = h & 1 ? C.char : C.charD;
      } else if (h / 255 < f.strength) {
        // burnt ground; fresh scars still have a few smoldering embers
        c =
          f.fresh && h % 23 === 0 && frame % 3 !== 0
            ? C.ember
            : h & 1
              ? C.char
              : C.charD;
      }
    }
  return c;
}

// ---------- sprites ----------
interface Sprite {
  rows: string[];
  pal: Record<string, string>;
}
const BUILDING_SPRITES: Record<string, Sprite> = {
  house: {
    rows: ["..R..", ".RRR.", "RRRRR", ".WWW.", ".WdW."],
    pal: { R: "#c8402c", W: "#efe2bc", d: "#3e2414" },
  },
  farm: {
    rows: ["OOOOOOO", "OWWWWWO", "OwwwwwO", "OWWWWWO", "OOOOOOO"],
    pal: { O: "#6e4c2a", W: "#d9bb4a", w: "#b8982e" },
  },
  pasture: {
    rows: ["F.F.F.F", "FFFFFFF", ".w..w..", ".wO.wO.", "FFFFFFF"],
    pal: { F: "#8a5a32", w: "#f4f4ec", O: "#1a120a" },
  },
  lumber: {
    rows: ["t..t.t.", "LLLLLL.", ".LLLLLL", "t.t..t."],
    pal: { t: "#5a3a1e", L: "#b07a45" },
  },
  grove: {
    rows: [".g...g.", "ggg.ggg", "gGg.gGg", ".t...t."],
    pal: { g: "#4f8f36", G: "#2d5e22", t: "#5a3a1e" },
  },
  kiln: {
    rows: ["..OOO..", ".ORRRO.", ".ORfRO.", ".OOOOO."],
    pal: { O: "#1a120a", R: "#d0613f", f: "#f5c542" },
  },
  mine: {
    rows: ["..KKK..", ".KdddK.", "KdddddK", "PPPPPPP"],
    pal: { K: "#776e60", d: "#1a120a", P: "#8a5a32" },
  },
  windmill: {
    rows: ["x.x", ".x.", "x.x", ".B.", ".B.", "BBB"],
    pal: { x: "#f4f4ec", B: "#8a5a32" },
  },
  wetland: {
    rows: ["b.g.b.g", "bbgbbbg", "gbbbgbb"],
    pal: { b: "#3a9bd2", g: "#4f8a32" },
  },
  cistern: {
    rows: [".OOO.", "ObbbO", "ObbbO", ".OOO."],
    pal: { O: "#9a9182", b: "#3a9bd2" },
  },
  firewatch: {
    rows: [".R.", "OOO", ".O.", ".O.", "O.O"],
    pal: { R: "#c8402c", O: "#8a5a32" },
  },
  terraces: {
    rows: ["GGGGG..", "SSSSS..", ".GGGGGG", ".SSSSSS"],
    pal: { G: "#5e9c3c", S: "#8a6238" },
  },
  filters: {
    rows: [".g.", "OOO", "OMO", "OMO", "OOO"],
    pal: { g: "#7fd65a", O: "#1a120a", M: "#9a9182" },
  },
  settling: {
    rows: ["OOOOOOO", "OsbsbsO", "OOOOOOO"],
    pal: { O: "#9a9182", s: "#6e6230", b: "#3a9bd2" },
  },
  mangroves: {
    rows: [".g.g.g.", "ggggggg", "t.t.t.t", "bbbbbbb"],
    pal: { g: "#2d5e22", t: "#5a3a1e", b: "#3a9bd2" },
  },
  shade: {
    rows: [".g..g.", "gggggg", "gGggGg", ".t..t."],
    pal: { g: "#6fae48", G: "#3d7a2e", t: "#5a3a1e" },
  },
  tsunami_warning: {
    rows: ["..RRR..", ".RRRRR.", "RRRRRRR", ".WWWWW.", ".WWdWW."],
    pal: { R: "#f5c542", W: "#efe2bc", d: "#3e2414" },
  },
};
const WINDMILL_SPIN = [".x.", "xxx", ".x.", ".B.", ".B.", "BBB"];

function blit(
  out: Uint8ClampedArray,
  rows: string[],
  pal: Record<string, string | RGB | undefined>,
  x0: number,
  y0: number,
  skip?: (ch: string, i: number, j: number) => boolean,
  topColor?: RGB,
) {
  // The first filled pixel in each column is the building's top edge (its roof).
  const topped = topColor ? new Uint8Array(rows[0]?.length ?? 0) : undefined;
  rows.forEach((row, j) => {
    for (let i = 0; i < row.length; i++) {
      const ch = row[i];
      const v = pal[ch];
      if (ch === "." || ch === " " || v === undefined || skip?.(ch, i, j))
        continue;
      const x = x0 + i,
        y = y0 + j;
      if (x < 0 || y < 0 || x >= MAP_W || y >= MAP_H) continue;
      let c = typeof v === "string" ? rgb(v) : v;
      if (topped && !topped[i]) {
        topped[i] = 1;
        c = topColor!;
      }
      const o = (y * MAP_W + x) * 4;
      out[o] = c[0];
      out[o + 1] = c[1];
      out[o + 2] = c[2];
      out[o + 3] = 255;
    }
  });
}
function puff(
  out: Uint8ClampedArray,
  x: number,
  y: number,
  frame: number,
  dark = false,
) {
  for (let p = 0; p < 3; p++) {
    const py = y - ((frame + p * 2) % 6),
      px = x + (p % 2);
    blit(out, ["s"], { s: dark ? C.smokeD : C.smoke }, px, py);
  }
}
/** Draw the whole world for `state` at animation `frame` into an RGBA buffer of MAP_W × MAP_H. */
export function renderWorld(
  state: GameState | undefined,
  frame: number,
  out: Uint8ClampedArray,
  traffic: PortTraffic[] = tradeTraffic(state, frame),
  strikeAge = Infinity,
) {
  const L = worldLayers();
  const status = areaStatus(state);
  // The reveal: hazards sweep in over STRIKE_FRAMES, then rage at full strength.
  const progress =
    state?.phase === "event"
      ? Math.max(0, Math.min(1, strikeAge / STRIKE_FRAMES))
      : 1;
  const fireList = fires(L, state, status, progress);
  const climate = state?.climate ?? 0;
  // Warmer seas are murkier seas.
  const ocean = 100 - climate * 12;
  for (let i = 0; i < MAP_W * MAP_H; i++) {
    const c = terrainPixel(
      L,
      i,
      frame,
      status,
      climate,
      ocean,
      progress,
      fireList,
    );
    out[i * 4] = c[0];
    out[i * 4 + 1] = c[1];
    out[i * 4 + 2] = c[2];
    out[i * 4 + 3] = 255;
  }
  const areaAt = (x: number, y: number) =>
    L.area[Math.min(MAP_H - 1, Math.max(0, y)) * MAP_W + x];
  for (const sp of world.sprites) {
    const fx =
      status[areaAt(sp.x + 1, sp.y + sp.rows.length - 1)]?.effects ??
      new Set<string>();
    if (sp.kind === "boat") {
      blit(out, sp.rows, sp.pal, sp.x, sp.y + ((frame >> 1) & 1));
    } else if (sp.kind === "lighthouse") {
      const on = frame % 4 < 2;
      blit(
        out,
        sp.rows,
        { ...sp.pal, y: on ? "#fff1b0" : "#3e2414" },
        sp.x,
        sp.y,
      );
      if (on) blit(out, ["y...y"], { y: "#f5c542" }, sp.x - 1, sp.y);
    } else if (sp.kind === "dam") {
      const broken = fx.has("dam_failure");
      blit(
        out,
        sp.rows,
        sp.pal,
        sp.x,
        sp.y,
        (_, i, j) => broken && j < 3 && i >= 4 && i <= 6,
      );
    } else {
      blit(out, sp.rows, sp.pal, sp.x, sp.y);
    }
  }
  // Flames over the burning area: a jittered lattice, densest along the advancing front, with smoke.
  for (const f of fireList) {
    if (f.burning) {
      let n = 0;
      for (let gy = f.cy - f.r; gy <= f.cy + f.r; gy += 5)
        for (let gx = f.cx - f.r; gx <= f.cx + f.r; gx += 5) {
          const jx = Math.round(gx + ((gx * 7 + gy * 3) % 3) - 1),
            jy = Math.round(gy + ((gx * 5 + gy * 11) % 3) - 1);
          if (jx < 1 || jy < 4 || jx >= MAP_W - 2 || jy >= MAP_H) continue;
          const i = jy * MAP_W + jx;
          if (!burnable(L.kind[i])) continue;
          const d = Math.hypot(jx - f.cx, jy - f.cy);
          if (d > f.r) continue;
          // the front always burns; the interior keeps about half its flames
          if (d < f.r - 6 && L.hash[i] & 1) continue;
          n++;
          blit(
            out,
            FLAME_TILES[(frame + n) % FLAME_TILES.length],
            FLAME,
            jx - 1,
            jy - 3,
          );
          if (n % 3 === 0) puff(out, jx, jy - 4, frame + n, true);
        }
    } else if (f.fresh) {
      // thin smoke still rising from the scar
      for (let n = 0; n < 4; n++) {
        const ang = n * 1.7 + f.a;
        puff(
          out,
          Math.round(f.cx + Math.cos(ang) * f.r * 0.5),
          Math.round(f.cy + Math.sin(ang) * f.r * 0.5) - 2,
          frame + n * 2,
        );
      }
    }
  }
  world.castles.forEach((k, a) => {
    const town = TOWNS[a],
      w = k.rows[0].length,
      st = status[a];
    // The town grows into its plots, nearest the keep first, in the order things were built.
    st.buildings.forEach((id, n) => {
      const slot = k.slots[n];
      if (!slot) return;
      const sprite = BUILDING_SPRITES[id] ?? BUILDING_SPRITES.house;
      const sw = sprite.rows[0].length,
        sh = sprite.rows.length;
      const x = slot[0] + Math.floor((7 - sw) / 2),
        y = slot[1] + 7 - sh;
      const rows = id === "windmill" && frame & 1 ? WINDMILL_SPIN : sprite.rows;
      // Roofs fly the town's colour so you can read ownership at a glance.
      blit(out, rows, sprite.pal, x, y, undefined, FLAG[town.civ]);
      if (id === "kiln") puff(out, x + 3, y - 1, frame + n);
    });
    // Villagers walk between the keep and the town's plots: tiny 1x3 people that show scale and
    // life. More of them appear as the town grows.
    const gateX = k.x + Math.floor(w / 2),
      gateY = k.y + k.rows.length + 1;
    const people = Math.min(10, 2 + st.buildings.length);
    const reach = Math.max(
      1,
      Math.min(k.slots.length, st.buildings.length + 4),
    );
    for (let i = 0; i < people; i++) {
      const slot = k.slots[(i * 5 + a) % reach];
      if (!slot) continue;
      const tx = slot[0] + 3,
        ty = slot[1] + 7;
      const dist = Math.max(1, Math.round(Math.hypot(tx - gateX, ty - gateY)));
      const t = (frame + i * 17) % (dist * 2);
      const along = (t < dist ? t : dist * 2 - t) / dist;
      const px = Math.round(gateX + (tx - gateX) * along),
        py = Math.round(gateY + (ty - gateY) * along);
      if (px < 0 || py < 1 || px >= MAP_W || py >= MAP_H - 1) continue;
      if (L.kind[py * MAP_W + px] <= KIND.water) continue; // no walking on water
      const step = (frame + i) & 1;
      blit(
        out,
        ["h", "b", step ? "l" : "."],
        { h: "#f2c79a", b: i % 3 ? FLAG[town.civ] : "#e8e0c8", l: "#3e2414" },
        px,
        py - 1,
      );
    }
    blit(out, k.rows, { ...k.pal, F: FLAG[town.civ] }, k.x, k.y);
    // Smoke over the keep: thick while the hazard rages, a thin wisp while it heals.
    if (st.damaged >= 1) {
      puff(out, k.x + 2, k.y + 2, frame, true);
      puff(out, k.x + w - 3, k.y + 3, frame + 3, true);
    } else if (st.damaged > 0.3) {
      puff(out, k.x + 2, k.y + 2, frame);
    }
  });
  // Each town has a berth; cargo sails out and returns after an actual bank exchange.
  for (const civ of CIV_IDS) drawPier(out, portRoute(civ)[0]);
  // Harborkeep is a working harbour: fishing boats always sail out and back off its port.
  const harbor = portRoute("archipelago");
  if (harbor.length > 1) {
    const boatRows = [".F.", ".s.", "sss", "BBB"];
    const boatPal = { F: FLAG.tidehaven, s: rgb("#efe2bc"), B: rgb("#8a5a32") };
    const PERIOD = 150;
    for (let b = 0; b < 3; b++) {
      const t = (((frame + b * 50) % PERIOD) / PERIOD) * 2;
      const along = 1 - Math.abs(t - 1); // ping-pong out to sea and back
      const [x, y] = harbor[Math.round(along * (harbor.length - 1))];
      blit(out, boatRows, boatPal, x - 1, y - 3 + (((frame + b) >> 1) & 1));
    }
  }
  for (const trip of traffic) {
    const route = portRoute(trip.civ);
    const t = trip.frame / OCEAN.trade.frames;
    const index = Math.min(
      route.length - 1,
      Math.floor((1 - Math.abs(t * 2 - 1)) * route.length),
    );
    const [x, y] = route[index];
    blit(
      out,
      ["..F..", "..FF.", "..F..", "BBBBB", ".BBB."],
      { F: FLAG[townOfVisual(trip.civ)], B: "#b07a45" },
      x - 2,
      y - 4 + ((frame >> 1) & 1),
    );
  }
}

/**
 * A wooden pier for a berth: it starts on the neighbouring land tile and runs straight out over the
 * water (away from the shore) for 3px, two planks wide with a dark edge, so it always touches land.
 */
function drawPier(out: Uint8ClampedArray, [bx, by]: [number, number]) {
  const L = worldLayers();
  const land = (x: number, y: number) =>
    x >= 0 &&
    y >= 0 &&
    x < MAP_W &&
    y < MAP_H &&
    L.kind[y * MAP_W + x] > KIND.water;
  const dirs: [number, number][] = [
    [0, -1],
    [0, 1],
    [-1, 0],
    [1, 0],
  ];
  const shore = dirs.find(([dx, dy]) => land(bx + dx, by + dy));
  if (!shore) return;
  const [ox, oy] = [-shore[0], -shore[1]]; // out toward open water
  const [px, py] = [-oy, ox]; // across the pier
  const plank = rgb("#b07a45"),
    edge = rgb("#6e4a28");
  for (let k = -1; k < 3; k++) {
    // k = -1 is the land end; 0..2 run over the water
    for (let w = 0; w < 2; w++) {
      const x = bx + ox * k + px * w,
        y = by + oy * k + py * w;
      if (x < 0 || y < 0 || x >= MAP_W || y >= MAP_H) continue;
      const c = w === 1 || k === 2 ? edge : plank;
      const o = (y * MAP_W + x) * 4;
      out[o] = c[0];
      out[o + 1] = c[1];
      out[o + 2] = c[2];
    }
  }
}

const townOfVisual = (civ: CivId) =>
  TOWNS.find((t) => OWNERS[t.civ] === civ)!.civ;
