// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const QuizClock = __t.object("QuizClock", {
  id: __t.string(),
  startedMicros: __t.u64(),
  questionId: __t.string(),
});
export type QuizClock = __Infer<typeof QuizClock>;

export const Room = __t.object("Room", {
  id: __t.string(),
  host: __t.identity(),
  revision: __t.u32(),
  stateJson: __t.string(),
});
export type Room = __Infer<typeof Room>;

export const Seat = __t.object("Seat", {
  id: __t.string(),
  roomId: __t.string(),
  identity: __t.identity(),
  civ: __t.string(),
  ready: __t.bool(),
});
export type Seat = __Infer<typeof Seat>;
