// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const QuizTimer = __t.object("QuizTimer", {
  id: __t.string(),
  worldId: __t.string(),
  questionId: __t.string(),
  startedMicros: __t.u64(),
});
export type QuizTimer = __Infer<typeof QuizTimer>;

export const Seat = __t.object("Seat", {
  id: __t.string(),
  worldId: __t.string(),
  identity: __t.identity(),
  civ: __t.string(),
  ready: __t.bool(),
  joinedMicros: __t.u64(),
});
export type Seat = __Infer<typeof Seat>;

export const World = __t.object("World", {
  id: __t.string(),
  host: __t.identity(),
  revision: __t.u32(),
  status: __t.string(),
  round: __t.u32(),
  phase: __t.string(),
  mode: __t.string(),
  started: __t.bool(),
  snapshotJson: __t.string(),
  updatedMicros: __t.u64(),
});
export type World = __Infer<typeof World>;

export const WorldState = __t.object("WorldState", {
  worldId: __t.string(),
  stateJson: __t.string(),
});
export type WorldState = __Infer<typeof WorldState>;
