// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  host: __t.identity(),
  revision: __t.u32(),
  status: __t.string(),
  round: __t.u32(),
  phase: __t.string(),
  mode: __t.string(),
  started: __t.bool(),
  snapshotJson: __t.string().name("snapshot_json"),
  updatedMicros: __t.u64().name("updated_micros"),
});
