// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ActReducer from "../act_reducer";
import AdvanceReducer from "../advance_reducer";
import AnswerReducer from "../answer_reducer";
import BeginQuestionReducer from "../begin_question_reducer";
import CreateWorldReducer from "../create_world_reducer";
import JoinWorldReducer from "../join_world_reducer";
import ReadyReducer from "../ready_reducer";
import StartWorldReducer from "../start_world_reducer";

export type ActParams = __Infer<typeof ActReducer>;
export type AdvanceParams = __Infer<typeof AdvanceReducer>;
export type AnswerParams = __Infer<typeof AnswerReducer>;
export type BeginQuestionParams = __Infer<typeof BeginQuestionReducer>;
export type CreateWorldParams = __Infer<typeof CreateWorldReducer>;
export type JoinWorldParams = __Infer<typeof JoinWorldReducer>;
export type ReadyParams = __Infer<typeof ReadyReducer>;
export type StartWorldParams = __Infer<typeof StartWorldReducer>;
